version: 1
disable_existing_loggers: true

formatters:
    standard:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    colored:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"
        (): "coloredlogs.ColoredFormatter"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: colored
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: INFO
        formatter: standard
        filename: logs/info.log
        when: midnight
        interval: 1
        backupCount: 10
        encoding: utf8
        delay: false

loggers:
    OPCUA_server_logger:
        level: INFO
        handlers: [console, info_file_handler]
        propogate: no

root:
    level: INFO
    handlers: [console, info_file_handler]
